name: Update Kanbanize

on:
  pull_request:
    types: [opened, edited]
  create:

jobs:
  update-kanbanize:
    runs-on: ubuntu-latest
    steps:
      - name: Update Kanbanize
        id: update-kanbanize
        uses: StrategicFS/DEV-GitHub-Actions/update-kanbanize@master
        with:
          kanbanize-api-key: ${{ secrets.KANBANIZE_API_KEY }}
