name: "Stop Web App"
description: "Stop an App Service / Func App / Standard Logic App"
inputs:
  app-name:
    description: "The Azure resource name of the app service to stop."
    required: true
runs:
  using: "composite"
  steps:
    - name: stop
      shell: bash
      run: |
        token=$(curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com' -H Metadata:true -s | jq -r .access_token)
        subscriptions=$(curl -X GET https://management.azure.com/subscriptions?api-version=2020-01-01 -H "Authorization: Bearer $token" | jq  -r '.value[].subscriptionId')
        for sub in $subscriptions; do
          app_id=$(curl -X GET "https://management.azure.com/subscriptions/$sub/resources?api-version=2021-04-01" -H "Authorization: Bearer $token" -H "Content-Type: application/json" | jq -r '.value[] | select(.name=="${{ inputs.app-name }}" and .type=="Microsoft.Web/sites") | .id')
          if [[ $app_id != "" ]]; then break; fi
        done
        curl -X POST --fail "https://management.azure.com${app_id}/stop?api-version=2021-02-01" -H "Authorization: Bearer $token" -H "Content-Type: application/json" -H "Content-Length: 0"
