name: 'Zip Deploy'
description: 'Zip deploy to an App Service / Func App / Standard Logic App zip deploy endpoint'
inputs:
  app-name:
    description: 'The Azure resource name of the app service to deploy to.'
    required: true
  package-location:
    description: 'The relative path to the zip package to deploy, if not in the current directory. Do not include the trailing slash.'
    required: false
    default: '.'
  local-development:
    description: 'Used for running this action on a runner connected to GitHub via a developer machine. For dev purposes only.'
    required: false
    default: false
runs:
  using: "composite"
  steps:
  - name: deploy
    shell: bash
    run: |
      if [ ${{inputs.local-development }} ]; 
        then curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash; token=$(az account get-access-token | jq -r .access_token)
        else token=$(curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com' -H Metadata:true -s | jq -r .access_token)
      fi
      subscriptions=$(curl -X GET https://management.azure.com/subscriptions?api-version=2020-01-01 -H "Authorization: Bearer $token" | jq  -r '.value[].subscriptionId')
      for sub in $subscriptions; do
        app_id=$(curl -X GET "https://management.azure.com/subscriptions/$sub/resources?api-version=2021-04-01" -H "Authorization: Bearer $token" -H "Content-Type: application/json" | jq -r '.value[] | select(.name=="${{ inputs.app-name }}" and .type=="Microsoft.Web/sites") | .id')
        if [[ $app_id != "" ]]; then break; fi
      done
      publishInfo=$(curl -X POST https://management.azure.com${app_id}/config/publishingcredentials/list?api-version=2019-08-01 -H "Authorization: Bearer $token" -H "Content-Type: application/json" -H "Content-Length: 0")
      publishName=$(jq -r '.properties.publishingUserName' <<<$publishInfo)
      publishPass=$(jq -r '.properties.publishingPassword' <<<$publishInfo)
      curl -XPOST --fail -u "$publishName:$publishPass" --data-binary @"${{ inputs.package-location }}/${{ inputs.app-name }}.zip" "https://${{ inputs.app-name }}.scm.azurewebsites.net/api/zipdeploy"
